version: '3.1'

services:

  my_db_chat:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
    - "3306"
    environment:
      MYSQL_DATABASE: chat
      MYSQL_ROOT_PASSWORD: admin

  my_chat:
    image: supermon/chat
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - my_db_chat
    links:
      - my_db_chat
